In [19]:
# Current data fromat 
# {"messages": [{"role": "system", "content": "You are an expert in trademark identification for apparel designs. Your task is to analyze images of apparel and determine if they contain licensed trademarks such as Greek organization letters (fraternities/sororities) or collegiate/university marks. Your response must strictly follow this two-line format: first indicating 'Licensed trademarks detected: Yes' or 'Licensed trademarks detected: No', followed by 'Organization:' with either the specific organization/university name(s) identified or 'None' if no trademarks are detected."}, 
#               {"role": "user", "content": [
#                     {"type": "text", "text": "Examine these apparel images and identify if they contain licensed marks or Greek letters. If yes, name the Greek organization or university associated."}, 
#                     {"type": "image_url", "image_url": {"url": "https://cf.freshprints.com/designs/1650260627094_front.jpeg"}}, 
#                     {"type": "image_url", "image_url": {"url": "https://cf.freshprints.com/designs/1650260627094_back.jpeg"}}
#                     ]}, 
#               {"role": "assistant", "content": "Licensed trademarks detected: Yes\nOrganization: Alabama - The University of"}]}

# {"messages": [{"role": "system", "content": "You are an expert in trademark identification for apparel designs. Your task is to analyze images of apparel and determine if they contain licensed trademarks such as Greek organization letters (fraternities/sororities) or collegiate/university marks. Your response must strictly follow this two-line format: first indicating 'Licensed trademarks detected: Yes' or 'Licensed trademarks detected: No', followed by 'Organization:' with either the specific organization/university name(s) identified or 'None' if no trademarks are detected."}, {"role": "user", "content": [{"type": "text", "text": "Examine these apparel images and identify if they contain licensed marks or Greek letters. If yes, name the Greek organization or university associated."}, {"type": "image_url", "image_url": {"url": "https://cf.freshprints.com/designs/1650136241773_front.jpeg"}}, {"type": "image_url", "image_url": {"url": "https://cf.freshprints.com/designs/1650136241773_back.jpeg"}}]}, {"role": "assistant", "content": "Licensed trademarks detected: Yes\nOrganization: Alabama - The University of"}]}
# {"messages": [{"role": "system", "content": "You are an expert in trademark identification for apparel designs. Your task is to analyze images of apparel and determine if they contain licensed trademarks such as Greek organization letters (fraternities/sororities) or collegiate/university marks. Your response must strictly follow this two-line format: first indicating 'Licensed trademarks detected: Yes' or 'Licensed trademarks detected: No', followed by 'Organization:' with either the specific organization/university name(s) identified or 'None' if no trademarks are detected."}, {"role": "user", "content": [{"type": "text", "text": "Examine these apparel images and identify if they contain licensed marks or Greek letters. If yes, name the Greek organization or university associated."}, {"type": "image_url", "image_url": {"url": "https://cf.freshprints.com/designs/1650135259441_front.jpeg"}}, {"type": "image_url", "image_url": {"url": "https://cf.freshprints.com/designs/1650135259441_back.jpeg"}}]}, {"role": "assistant", "content": "Licensed trademarks detected: Yes\nOrganization: Alabama - The University of"}]}

### Extracting necessary data

In [1]:
import pandas as pd

path = "trademark_detection.jsonl"
# Create DataFrame
df = pd.read_json(path, lines=True)

def extract_image_urls(row):
    images = []
    for msg in row['messages']:
        if msg['role'] == 'user' and isinstance(msg['content'], list):
            for content in msg['content']:
                if 'image_url' in content:
                    images.append(content['image_url']['url'])
    return images # ", ".join(images)

# Extract detection status and organization
def extract_info(row):
    for msg in row['messages']:
        if msg['role'] == 'assistant':
            detected = msg['content'].split('\n')[0].split(': ')[1]
            organization = msg['content'].split('\n')[1].split(': ')[1]
            return pd.Series([detected, organization])
    return pd.Series([None, None])


df['image_urls'] = df.apply(extract_image_urls, axis=1)
df[['trademark_detected', 'organization']] = df.apply(extract_info, axis=1)

### Data analysis

In [2]:
df

,messages,image_urls,trademark_detected,organization
0,"[{'role': 'system', 'content': 'You are an exp...",[https://cf.freshprints.com/designs/1650260627...,Yes,Alabama - The University of
1,"[{'role': 'system', 'content': 'You are an exp...",[https://cf.freshprints.com/designs/1650136241...,Yes,Alabama - The University of
2,"[{'role': 'system', 'content': 'You are an exp...",[https://cf.freshprints.com/designs/1650135259...,Yes,Alabama - The University of
3,"[{'role': 'system', 'content': 'You are an exp...",[https://cf.freshprints.com/designs/1643236625...,Yes,Alabama - The University of
4,"[{'role': 'system', 'content': 'You are an exp...",[https://cf.freshprints.com/designs/1643236624...,Yes,Alabama - The University of
...,...,...,...,...
144173,"[{'role': 'system', 'content': 'You are an exp...",[https://res.cloudinary.com/dsnai3oon/image/up...,Yes,Worcester Polytechnic Institute (WPI)
144174,"[{'role': 'system', 'content': 'You are an exp...",[https://res.cloudinary.com/dsnai3oon/image/up...,Yes,Worcester Polytechnic Institute (WPI)
144175,"[{'role': 'system', 'content': 'You are an exp...",[https://res.cloudinary.com/dsnai3oon/image/up...,Yes,Worcester Polytechnic Institute (WPI)
144176,"[{'role': 'system', 'content': 'You are an exp...",[https://res.cloudinary.com/dsnai3oon/image/up...,Yes,Worcester Polytechnic Institute (WPI)
144177,"[{'role': 'system', 'content': 'You are an exp...",[https://res.cloudinary.com/dsnai3oon/image/up...,Yes,Worcester Polytechnic Institute (WPI)

In [3]:
max(df['image_urls'].apply(lambda x: len(x))),min(df['image_urls'].apply(lambda x: len(x)))

(2, 1)

In [ ]:
df['image_urls'][0]

['https://cf.freshprints.com/designs/1650260627094_front.jpeg',
 'https://cf.freshprints.com/designs/1650260627094_back.jpeg']

In [5]:
df['trademark_detected'].value_counts()

trademark_detected
Yes    127657
No      16521
Name: count, dtype: int64

In [6]:
df['organization'].value_counts()

organization
None                        16521
Alpha Phi                    5949
Kappa Kappa Gamma            5901
Kappa Alpha Theta            5744
Alpha Delta Pi               5680
                            ...
for fun                         1
DOL                             1
Design Tool org                 1
Delta Theta                     1
West Virginia University        1
Name: count, Length: 451, dtype: int64

In [10]:
df[df['trademark_detected'] == 'No']

,messages,image_urls,trademark_detected,organization
105657,"[{'role': 'system', 'content': 'You are an exp...",[https://cf.freshprints.com/designs/fbf0c79f-c...,No,None
105658,"[{'role': 'system', 'content': 'You are an exp...",[https://cf.freshprints.com/designs/baf76059-a...,No,None
105659,"[{'role': 'system', 'content': 'You are an exp...",[https://cf.freshprints.com/designs/1733346671...,No,None
105660,"[{'role': 'system', 'content': 'You are an exp...",[https://cf.freshprints.com/designs/1731980375...,No,None
105661,"[{'role': 'system', 'content': 'You are an exp...",[https://cf.freshprints.com/designs/1731979416...,No,None
...,...,...,...,...
141600,"[{'role': 'system', 'content': 'You are an exp...",[https://cf.freshprints.com/designs/1734012859...,No,None
141601,"[{'role': 'system', 'content': 'You are an exp...",[https://cf.freshprints.com/designs/1734096942...,No,None
141602,"[{'role': 'system', 'content': 'You are an exp...",[https://cf.freshprints.com/designs/1734350372...,No,None
141603,"[{'role': 'system', 'content': 'You are an exp...",[https://cf.freshprints.com/designs/1734350442...,No,None
141604,"[{'role': 'system', 'content': 'You are an exp...",[https://cf.freshprints.com/designs/1734357738...,No,None

### Balancing dataset

In [11]:
df_grouped_by = df.groupby(['trademark_detected'])
df_balanced = df_grouped_by.apply(lambda x: x.sample(df_grouped_by.size().min()).reset_index(drop=True), include_groups=True).droplevel(1).reset_index(drop=True)
df_balanced['trademark_detected'].value_counts()

/tmp/ipykernel_188947/4065282333.py:2: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df_balanced = df_grouped_by.apply(lambda x: x.sample(df_grouped_by.size().min()).reset_index(drop=True), include_groups=True).droplevel(1).reset_index(drop=True)

trademark_detected
No     16521
Yes    16521
Name: count, dtype: int64

### Creating huggingface dataset

In [17]:
from sklearn.model_selection import train_test_split
train_df, test_df = train_test_split(df_balanced, test_size=0.5, random_state=42, stratify=df_balanced['trademark_detected'])
val_df, test_df = train_test_split(test_df.reset_index(drop=True), test_size=0.5, random_state=42, stratify=test_df['trademark_detected'])

In [19]:
train_df.shape, val_df.shape, test_df.shape

((16521, 4), (8260, 4), (8261, 4))

In [20]:
from datasets import Dataset, DatasetDict, Features, Value


def create_split_dataset(df):

    return Dataset.from_dict({
        'image_urls': df['image_urls'],
        'trademark_detected': df['trademark_detected'],
        'organization': df['organization']
    }, features=Features({
        'image_urls': [Value('string')],  # Supports multiple image_urls per sample
        'trademark_detected': Value('string'),
        'organization': Value('string')
    }))

# Create train and test datasets
train_dataset = create_split_dataset(train_df)
val_dataset = create_split_dataset(val_df)
test_dataset = create_split_dataset(test_df)




# Create DatasetDict
dataset = DatasetDict({
    'train': train_dataset,
    'val': val_dataset,
    'test': test_dataset
})

In [21]:
dataset

DatasetDict({
    train: Dataset({
        features: ['image_urls', 'trademark_detected', 'organization'],
        num_rows: 16521
    })
    val: Dataset({
        features: ['image_urls', 'trademark_detected', 'organization'],
        num_rows: 8260
    })
    test: Dataset({
        features: ['image_urls', 'trademark_detected', 'organization'],
        num_rows: 8261
    })
})

In [22]:
dataset['train'][0]

{'image_urls': ['https://cf.freshprints.com/designs/1726115067846ljkcb_nt_front.png',
  'https://cf.freshprints.com/designs/1726115067846fvuus_nt_back.png'],
 'trademark_detected': 'Yes',
 'organization': 'Kappa Alpha Theta'}

In [23]:
from huggingface_hub import login
import os 
# Login into Hugging Face Hub
login(os.getenv("HF_TOKEN"))
dataset.push_to_hub("ikram98ai/trademark_detection")

Note: Environment variable`HF_TOKEN` is set and is the current active token independently from the token you've just configured.

Uploading the dataset shards:   0%|          | 0/1 [00:00<?, ?it/s]

Creating parquet from Arrow format:   0%|          | 0/17 [00:00<?, ?ba/s]

Uploading the dataset shards:   0%|          | 0/1 [00:00<?, ?it/s]

Creating parquet from Arrow format:   0%|          | 0/9 [00:00<?, ?ba/s]

Uploading the dataset shards:   0%|          | 0/1 [00:00<?, ?it/s]

Creating parquet from Arrow format:   0%|          | 0/9 [00:00<?, ?ba/s]

CommitInfo(commit_url='https://huggingface.co/datasets/ikram98ai/trademark_detection/commit/25d8bcbf5a998de971d74263e2d92ea373005dd9', commit_message='Upload dataset', commit_description='', oid='25d8bcbf5a998de971d74263e2d92ea373005dd9', pr_url=None, repo_url=RepoUrl('https://huggingface.co/datasets/ikram98ai/trademark_detection', endpoint='https://huggingface.co', repo_type='dataset', repo_id='ikram98ai/trademark_detection'), pr_revision=None, pr_num=None)

In [24]:
system_prompt = """You are an expert in trademark identification for apparel designs. Your task is to analyze images of apparel and determine 
if they contain licensed trademarks such as Greek organization letters (fraternities/sororities) or collegiate/university marks. Your response 
must strictly follow this two-line format: first indicating 'Licensed trademarks detected: Yes' or 'Licensed trademarks detected: No', followed 
by 'Organization:' with either the specific organization/university name(s) identified or 'None' if no trademarks are detected."""

instruction = """Examine these apparel images and identify if they contain licensed marks or Greek letters. If yes, name the Greek organization or university associated."""

In [25]:
from datasets import load_dataset

train_dataset = load_dataset("ikram98ai/trademark_detection", split="train")
test_dataset = load_dataset("ikram98ai/trademark_detection", split="test")
val_dataset = load_dataset("ikram98ai/trademark_detection", split="val")

README.md:   0%|          | 0.00/563 [00:00<?, ?B/s]

train-00000-of-00001.parquet:   0%|          | 0.00/554k [00:00<?, ?B/s]

val-00000-of-00001.parquet:   0%|          | 0.00/279k [00:00<?, ?B/s]

test-00000-of-00001.parquet:   0%|          | 0.00/278k [00:00<?, ?B/s]

Generating train split:   0%|          | 0/16521 [00:00<?, ? examples/s]

Generating val split:   0%|          | 0/8260 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/8261 [00:00<?, ? examples/s]

In [26]:
train_dataset

Dataset({
    features: ['image_urls', 'trademark_detected', 'organization'],
    num_rows: 16521
})

In [17]:

def convert_to_conversation(sample):
    conversation = [
        { "role": "user",
          "content" : [
            {"type" : "text",  "text"  : system_prompt + "\n\n" + instruction},
            ] + [{"type" : "image", "image" : image_url} for image_url in sample["image_urls"]]
        },
        { "role" : "assistant",
          "content" : [
            {"type" : "text",  "text"  : f"Licensed trademarks detected: {sample['trademark_detected']}\nOrganization:: {sample['organization']}"} ]
        },
    ]
    return { "messages" : conversation }

In [18]:
con_train_dataset = [convert_to_conversation(sample) for sample in train_dataset]
con_test_dataset = [convert_to_conversation(sample) for sample in test_dataset]